### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by xrotwang** [lexibank/tppsr#16]
I think we should add Hans as contributor, otherwise we can't really use the citation recommendation from Zenodo:

> Johann-Mattis List. (2020). CLDF dataset derived from Gauchat et al.'s "Tableaux phonétiques des patois suisses romands" from 1925 (Version v1.0) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.3988472

for the web app. What do you think?

**Comment by LinguList** [comment]
Yes, I was thinking the same, wanted to bring this up later. Hans is also providing the original digitization. I think, it is best, we just list the three of us as editors here, as we all worked on the data now, with Hans as first author (given that this is his project from long time ago etc.)
